#!/bin/sh -e

# # Postgresql Konfiguration

POSTGRESQL_USER="sfmonline"
POSTGRESQL_LINE_PG_HBA="local all $POSTGRESQL_USER password"
POSTGRESQL_PG_HBA_FILE=`su -c "psql -t -P format=unaligned -c 'show hba_file';" postgres`

if [ "$1" = configure ]; then

  echo "PostgreSQL: create user '$POSTGRESQL_USER' with password ..."
  su -c "createuser --no-superuser --no-createrole --pwprompt --encrypted --createdb $POSTGRESQL_USER" postgres

  echo "PostgreSQL: add user '$POSTGRESQL_USER' to '$POSTGRESQL_PG_HBA_FILE'"
  if ! grep -q "$POSTGRESQL_LINE_PG_HBA" $POSTGRESQL_PG_HBA_FILE ; then
    echo "PostgreSQL: Eintrag noch nicht vorhanden! Eintragen..."
    printf %"s\n" \
        "$POSTGRESQL_LINE_PG_HBA" \
    | sudo tee --append $POSTGRESQL_PG_HBA_FILE
  else
    echo "PostgreSQL: Eintrag bereits vorhanden! Ueberspringe..."
  fi

  service postgresql reload

  echo "ruby: install gems"
  /utils/install_gems_sfmonline.sh

  
  echo -e '\e[32mINSTALLATION OF SFMONLINE COMPLETE! \e[0m'

fi

exit 0
